name: legal_contracts_insights
channels:
  - defaults
dependencies:
  - python=3.12.8
  - numpy=2.2.1
  - pandas=2.2.3
  - plotly=5.24.1
  - nbformat>=4.2.0
  - scipy=1.15.1
  - nltk=3.9.1
  - wordcloud=1.9.4
  - fastapi=0.115.6
  - fastapi[standard]=0.115.6
  - motor=3.6.1
  - uvicorn=0.34.0
  - nest-asyncio=1.6.0
  - pymongo=4.9
  - openai=1.69.0
  - scikit-learn=1.6.1
  - fitz=0.0.1.dev2
  - tiktoken=0.9.0
  - frontend=0.0.3
  - pymupdf=1.25.4